# Generated by Django 4.0.5 on 2022-07-07 15:58

import uuid

from django.db import migrations, models

import app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[app.models.validate_login],
                    ),
                ),
                ("public", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[app.models.validate_login],
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                ("birth_date", models.DateField()),
                (
                    "groups",
                    models.ManyToManyField(blank=True, null=True, to="app.group"),
                ),
            ],
        ),
    ]
