# Generated by Django 4.0.5 on 2022-07-01 18:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("982e1416-6100-40c4-9690-39d086bcb4aa"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("login", models.CharField(max_length=16, unique=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                ("birth_date", models.DateTimeField()),
            ],
        ),
    ]
